### ISSUE TITLE
small fix in 

### ISSUE THREAD

**Issue by fliem** [csudre/EvaluationCharacterisation#1]
Hi,
I was looking for an implementation of the Wack et al. metrics and stumbled across your code. Thanks.

I think there is a small issue [here](https://github.com/csudre/EvaluationCharacterisation/blob/caa98e4a51c4dfacba5823956a7cd114f7fa6961/evaluation_comparison/pairwise_measures.py#L432):

I think
```
        list_blobs_ref = range(1, blobs_ref[1])
        list_blobs_seg = range(1, blobs_seg[1])
```
should be 
```
        list_blobs_ref = range(1, blobs_ref[1] + 1)
        list_blobs_seg = range(1, blobs_seg[1] + 1)
```

as range's stop index in non-inclusive and the current code misses the last blob
```
In [3]: list(range(1,2))                                                        
Out[3]: [1]
```

Also, is there a way to cite your work?

**Comment by csudre** [comment]
Thanks a lot for pointing it out @fliem - That has been corrected.
Please do mention this github page if you want to reference it. 
This has also been used in an associated paper - Fiford, C.M., Sudre, C.H. et al. Automated White Matter Hyperintensity Segmentation Using Bayesian Model Selection: Assessment and Correlations with Cognitive Change. Neuroinform (2020). https://doi.org/10.1007/s12021-019-09439-6
